# -*- coding: utf-8 -*-
"""Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WmZK-6cxlOUXDn3_ApjFUI9PI3M6vVsd
"""

# ============================================================
# 1. LINEAR REGRESSION
# Economic Example: Wage Prediction
# ============================================================

# Install/import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ------------------------------------------------------------
# STEP 1: Create a sample economic dataset
# ------------------------------------------------------------

np.random.seed(42)

n = 200

education = np.random.randint(8, 21, n)
experience = np.random.randint(0, 31, n)

# Generate wages using an economic relationship
wage = (
    5
    + 2.5 * education
    + 1.2 * experience
    - 0.02 * experience**2
    + np.random.normal(0, 5, n)
)

df = pd.DataFrame({
    "education_years": education,
    "experience_years": experience,
    "hourly_wage": wage
})

print("Sample Dataset:")
display(df.head())

# ------------------------------------------------------------
# STEP 2: Define X and y
# ------------------------------------------------------------

X = df[["education_years", "experience_years"]]
y = df["hourly_wage"]

# ------------------------------------------------------------
# STEP 3: Split into training and testing data
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42
)

# ------------------------------------------------------------
# STEP 4: Train Linear Regression
# ------------------------------------------------------------

model = LinearRegression()

model.fit(X_train, y_train)

# ------------------------------------------------------------
# STEP 5: Make predictions
# ------------------------------------------------------------

y_pred = model.predict(X_test)

# ------------------------------------------------------------
# STEP 6: Evaluate the model
# ------------------------------------------------------------

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("\nModel Results")
print("-------------------------")
print("Intercept:", model.intercept_)
print("Education coefficient:", model.coef_[0])
print("Experience coefficient:", model.coef_[1])
print("MAE:", round(mae, 3))
print("RMSE:", round(rmse, 3))
print("R²:", round(r2, 3))

# ------------------------------------------------------------
# STEP 7: Visualize actual vs predicted wages
# ------------------------------------------------------------

plt.figure(figsize=(7, 5))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Wage")
plt.ylabel("Predicted Wage")
plt.title("Linear Regression: Actual vs Predicted Wage")

plt.show()

# ------------------------------------------------------------
# ECONOMIC INTERPRETATION
# ------------------------------------------------------------

print("""
Economic Interpretation:

The model estimates how education and experience are associated
with predicted hourly wages.

A positive education coefficient indicates that higher education
is associated with higher predicted wages, holding experience
constant.

IMPORTANT:
This predictive relationship should not automatically be
interpreted as a causal effect.
""")