# -*- coding: utf-8 -*-
"""Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WmZK-6cxlOUXDn3_ApjFUI9PI3M6vVsd
"""

# ============================================================
# 2. LOGISTIC REGRESSION
# Economic Example: Loan Default Prediction
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    ConfusionMatrixDisplay
)

# ------------------------------------------------------------
# STEP 1: Create sample financial data
# ------------------------------------------------------------

np.random.seed(42)

n = 500

income = np.random.normal(60000, 15000, n)
credit_score = np.random.normal(680, 60, n)
debt_ratio = np.random.uniform(0.1, 0.9, n)

# Create probability of default
logit = (
    -3
    + 3.5 * debt_ratio
    - 0.006 * (credit_score - 680)
    - 0.00001 * (income - 60000)
)

probability = 1 / (1 + np.exp(-logit))

default = np.random.binomial(1, probability)

df = pd.DataFrame({
    "income": income,
    "credit_score": credit_score,
    "debt_to_income": debt_ratio,
    "default": default
})

display(df.head())

# ------------------------------------------------------------
# STEP 2: Define variables
# ------------------------------------------------------------

X = df[
    [
        "income",
        "credit_score",
        "debt_to_income"
    ]
]

y = df["default"]

# ------------------------------------------------------------
# STEP 3: Train-test split
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# ------------------------------------------------------------
# STEP 4: Train Logistic Regression
# ------------------------------------------------------------

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

# ------------------------------------------------------------
# STEP 5: Predictions
# ------------------------------------------------------------

y_pred = model.predict(X_test)

# Probability of default
y_probability = model.predict_proba(X_test)[:, 1]

# ------------------------------------------------------------
# STEP 6: Evaluation
# ------------------------------------------------------------

print("Accuracy:", round(accuracy_score(y_test, y_pred), 3))
print("Precision:", round(precision_score(y_test, y_pred), 3))
print("Recall:", round(recall_score(y_test, y_pred), 3))
print("F1 Score:", round(f1_score(y_test, y_pred), 3))
print("ROC-AUC:", round(roc_auc_score(y_test, y_probability), 3))

# ------------------------------------------------------------
# STEP 7: Confusion Matrix
# ------------------------------------------------------------

cm = confusion_matrix(y_test, y_pred)

display = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["No Default", "Default"]
)

display.plot()

plt.title("Loan Default Classification")

plt.show()

# ------------------------------------------------------------
# ECONOMIC INTERPRETATION
# ------------------------------------------------------------

print("""
Economic Interpretation:

The model estimates the probability that a borrower will default.

Credit score, income and debt-to-income ratio are used to
calculate the predicted probability of default.

This type of model can support credit-risk assessment.

However, real-world credit models require careful treatment
of fairness, regulation, data quality and class imbalance.
""")